
// user api

POST http://127.0.0.1:9000/api/consultation HTTP/1.1
Content-Type: application/json

{
  "consultation_code":"dssdfsf",
  "user_code":"dsfsd",
  "user_name":"dfsd",
  "consultation_date":"2016-12-13T06:55:24.698Z",
  "service_libelle":"sadsdas",
  "patient_card_code":"asdas",
  "patient_code":"sada",
  "patient_name":"asdasd"
    
}

###
GET http://127.0.0.1:9000/api/patient_cards/644e98fe5e30334e3892db2d HTTP/1.1

###
GET http://127.0.0.1:9000/api/consultations/644c451f7c80fc0a41a9f7bf HTTP/1.1

###
POST http://127.0.0.1:9000/api/login HTTP/1.1
Content-Type: application/json

{
  "user_code": "TAKECARE237",
  "password": "TakeCare"
}

###
PUT http://127.0.0.1:9000/api/patient/644b559089967196da3f923c HTTP/1.1
Content-Type: application/json

{
  "patient_code": "P1CODE",
  "first_name": "P1FName",
  "last_name": "P1LName",
  "address": "logbessou",
  "inscription_date": "2016-12-13T06:55:24.698Z",
  "birthday": "2016-12-13T06:55:24.698Z",
  "age": "0",
  "gender": "M",
  "assurance": "true",
  "phone": "655",
  "picture": "p1",
  "marital_status": "MS1",
  "emergency_number": "false",
  "occupation": "OCP1",
  "password": "pwd1" 
}

###
DELETE http://127.0.0.1:9000/api/service/644e2be0f5ab22401c44033d HTTP/1.1



// service api
###
POST http://127.0.0.1:9000/api/patient_card HTTP/1.1
Content-Type: application/json

{
  "user_code": "req.body.user_code",
  "user_name": "req.body.user_name",
  "consultation_code": "req.body.consultation_code",
  "consultation_details": "req.body.consultation_details",
  "examinations": [
    {
      "libelle":"liiiiibbbbeeeleeee",
      "result":"resullllllttt"
    }
  ],
  "patient_code": "req.body.patient_code",
  "patient_name": "req.body.patient_name"
}

###
GET http://127.0.0.1:9000/api/appointments/644e3af1b90d634b68ee8c0f HTTP/1.1

###

POST http://127.0.0.1:9000/api/appointment HTTP/1.1
Content-Type: application/json

{
  "date_of_appointment": "2016-12-13T06:55:24.698Z",
  "appointment_hour": "06:55:24",  
  "service_id": "6446dea87abf0e2de7e6653a",
  "user_id": "644789359cd2334e4633e467",
  "patient_id": "644b5b31fc0acc555d9de211"
}